source 'https://rubygems.org'

# Developed with:
# ruby '2.2.2'
# gem 'rails', '4.2.1'

# Database
gem 'pg'

# More from Rails
gem 'sass-rails', '~> 5.0' # Use SCSS for stylesheets
gem 'uglifier', '>= 1.3.0' # Use Uglifier as compressor for JavaScript assets
gem 'therubyracer', platforms: :ruby # See https://github.com/rails/execjs#readme for more supported runtimes
gem 'jbuilder', '~> 2.0' # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'sdoc', '~> 0.4.0', group: :doc # bundle exec rake doc:rails generates the API under doc/api.
gem 'unicorn' # Use Unicorn as the app server

# Administration
gem 'activeadmin', github: 'activeadmin'

# Authentication and Authorization
gem 'devise' # For user authentication

# Deployment
group :development, :test do
  gem 'capistrano', "~> 3.4"
  gem 'capistrano-rails', require: false
  gem 'capistrano-rvm', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano-unicorn-nginx', require: false
  gem 'capistrano-safe-deploy-to', require: false
  gem 'capistrano-npm', require: false
end

# Others
gem 'recursive-open-struct' # OpenStruct that supports nested hashes, used for app config
gem 'mechanize' # Makes automated web interaction easy
gem 'state_machines-activerecord' # Create state machines for attributes on any ruby class
gem 'friendly_id' # Friendly URLs
gem 'colorize' # String class extension. Adds methods to set color and text effect on console
gem 'octokit' # Official Ruby toolkit for the GitHub API
gem 'progress_bar', require: false # Terminal progress bar used by some rake tasks
gem 'pg_search' # Named scopes that take advantage of PostgreSQL's full text search
gem 'draper' # Presentation logic for resources using decorators
gem 'kaminari' # For pagination
gem 'memoist' # ActiveSupport::Memoizable with a few enhancements
gem 'exception_notification' # Exception notifier for Rails
gem 'slack-notifier' # Slack integration for the `exception_notification` gem
gem 'redcarpet' # The safe Markdown parser, reloaded
gem 'whenever', require: false # Cron jobs
gem 'twitter', require: false

# Gems used for both development and testing
group :development, :test do
  gem 'byebug' # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'web-console', '~> 2.0' # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'spring' # Spring speeds up development by keeping your application running in the background
  gem 'dotenv-rails' # Shim to load environment variables from .env into ENV in development
  gem 'pry-rails' # An IRB alternative and runtime developer console
end

# Gems used only for tests
group :test do
  gem 'minitest' # For a newer version than the one that comes with ruby 1.9
  gem 'minitest-spec-rails' # Make Rails use MiniTest::Spec
  gem 'minitest-metadata', require: false # Annotate tests (eg: `it "...", js: true do`)
  gem 'minitest-rg' # Adds red/green color to your Minitest output
  gem 'database_cleaner' # Ensure a clean database during tests
  gem 'capybara' # Simulates how a user would interact with the app
  gem 'capybara_minitest_spec' # MiniTest expectations for Capybara
  gem 'poltergeist' # A PhantomJS driver for Capybara (requires `phantomjs` installation)
  gem 'fakeweb', github: "chrisk/fakeweb" # A test helper for faking responses to web requests
end
