module ApplicationHelper
  # Helpers to include assets generated by webpack (with their digests) in our views
  # Based on: http://clarkdave.net/2015/01/how-to-use-webpack-with-rails/
  def webpack_bundle_tag(bundle)
    src =
      if Rails.configuration.webpack[:use_manifest]
        manifest = Rails.configuration.webpack[:asset_manifest]
        filename = manifest[bundle]

        "/assets/#{ filename }"
      else
        "#{ bundle }-bundle"
      end

    javascript_include_tag(src)
  end

  def webpack_manifest_script
    return "" unless Rails.configuration.webpack[:use_manifest]

    manifest = Rails.configuration.webpack[:common_manifest]
    javascript_tag "window.webpackManifest = #{ manifest.to_json }"
  end

  def react_render(props)
    js = "serverRender('#{ request.fullpath }', #{ props.to_json })"
    html, title = server_context.eval(js)
    content_for :title, title
    html.html_safe
  end

  private

  def server_context(filename: File.join(Rails.root, "server-bundle.js"))
    @_server_context ||= ExecJS.compile open(filename).read
  end
end
